### ISSUE TITLE
IO_ModeTypedef is not defined

### ISSUE THREAD

**Issue by firmwareguru** [STMicroelectronics/32l496gdiscovery#1]
When building a project utilizing the `32l496gdiscovery` BSP, the build encounters a missing type name `IO_ModeTypedef`.

In particular, the file stm32l496g_discovery_io.h/.c references IO_ModeTypedef, but is not brought into scope through any include path.  I am setting up a project that is using *git submodules* to pull in all STM32 firmware dependencies.  So, all sources in `Drivers` are from the master branches of the relevant source repositories found at https://github.com/STMicroelectronics.

I have investigated the issue and what has changed is the dependent library https://github.com/STMicroelectronics/stm32-mfxstm32l152.  It used to refer to `../Common/io.h` which had this type, but has since removed that #include reference, and is using `uint32_t` instead of `IO_ModeTypedef`.  I would suggest the same change needs to be made to this library if it is to continue to work with the associated dependencies from https://github.com/STMicroelectronics.

For reference, when build the project with STM32CubeIDE:

```
C:/fm/github/stm32-secure-patching-bootloader-demoapp/Drivers/BSP/STM32L496G-Discovery/stm32l496g_discovery_io.h:101:44: error: unknown type name 'IO_ModeTypedef'; did you mean 'JOYMode_TypeDef'?
 uint8_t  BSP_IO_ConfigPin(uint32_t IO_Pin, IO_ModeTypedef IO_Mode);
```

There may be other incompatibilities between this repository and dependencies like https://github.com/STMicroelectronics/stm32-mfxstm32l152.

**Comment by firmwareguru** [comment]
I examined the dependencies between these libraries and it builds if the following versions are observed:

| library | version |
| --- | --- |
| [stm32-bsp-common](https://github.com/STMicroelectronics/stm32-bsp-common/tree/v5.1.2) | v5.1.2 |
| [stm32-mfxstm32l152](https://github.com/STMicroelectronics/stm32-mfxstm32l152/tree/v2.0.3) | v2.0.3 |
| [32l496gdiscovery](https://github.com/STMicroelectronics/32l496gdiscovery/tree/v1.1.6) | v1.1.6 |

Note that bsp-common is at v7.1.0 and mfxstm32l152 is at v3.0.3.

**Comment by ALABSTM** [comment]
Hi @firmwareguru,

As you pointed out and as indicated by the [Compatibility information](https://github.com/STMicroelectronics/32l496gdiscovery/blob/main/README.md#compatibility-information) paragraph in the `README.md` file, it is crucial to pick up the **correct versions** of the different BSP Components' drivers to be used along with a BSP Board's driver.

These versions are indicated in the [Relase_Notes.html](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeL4/blob/master/Release_Notes.html) file of the [STM32CubeL4](https://github.com/STMicroelectronics/STM32CubeL4) firmware.

Regarding versions **v7.1.0** of the `BSP-COMMON` and **v3.0.3** of the `MFXSTM32L152`, these are to be used along with other BSP Boards' drivers (L5xx boards, for example).

I hope this makes things clearer. Please allow me to close this issue.

With regards,

**PS:** Best wishes for the new year 2022.
